# Generated by Django 6.0 on 2025-12-13 17:31

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FloodPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Vị trí')),
                ('address', models.CharField(max_length=300, verbose_name='Địa chỉ')),
                ('district', models.CharField(max_length=100, verbose_name='Quận')),
                ('prediction_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời điểm dự đoán')),
                ('risk_level', models.CharField(choices=[('very_low', 'Rất thấp'), ('low', 'Thấp'), ('medium', 'Trung bình'), ('high', 'Cao'), ('very_high', 'Rất cao')], max_length=20, verbose_name='Mức độ nguy cơ')),
                ('predicted_depth_cm', models.FloatField(default=0, verbose_name='Độ sâu dự đoán (cm)')),
                ('confidence', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Độ tin cậy (%)')),
                ('rainfall_mm', models.FloatField(verbose_name='Lượng mưa (mm/h)')),
                ('elevation', models.FloatField(help_text='So với mực nước biển', verbose_name='Độ cao (m)')),
                ('distance_to_river', models.FloatField(default=1000, verbose_name='Khoảng cách đến sông (m)')),
                ('drainage_capacity', models.CharField(choices=[('good', 'Tốt'), ('average', 'Trung bình'), ('poor', 'Kém')], max_length=50, verbose_name='Khả năng thoát nước')),
                ('reasons', models.JSONField(default=list, verbose_name='Nguyên nhân dự đoán')),
                ('recommendations', models.TextField(blank=True, verbose_name='Khuyến nghị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dự đoán ngập',
                'verbose_name_plural': 'Dự đoán ngập',
                'ordering': ['-prediction_time'],
            },
        ),
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Vị trí')),
                ('location_name', models.CharField(default='Hà Nội', max_length=200, verbose_name='Tên khu vực')),
                ('current_temp', models.FloatField(verbose_name='Nhiệt độ hiện tại (°C)')),
                ('current_humidity', models.FloatField(verbose_name='Độ ẩm hiện tại (%)')),
                ('current_rainfall', models.FloatField(default=0, verbose_name='Lượng mưa hiện tại (mm/h)')),
                ('current_description', models.CharField(max_length=100, verbose_name='Mô tả')),
                ('current_icon', models.CharField(max_length=10, verbose_name='Icon thời tiết')),
                ('forecast_3h', models.JSONField(default=dict, verbose_name='Dự báo 3h')),
                ('forecast_24h', models.JSONField(default=dict, verbose_name='Dự báo 24h')),
                ('alerts', models.JSONField(blank=True, default=list, verbose_name='Cảnh báo')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valid_until', models.DateTimeField(verbose_name='Hiệu lực đến')),
            ],
            options={
                'verbose_name': 'Dự báo thời tiết',
                'verbose_name_plural': 'Dự báo thời tiết',
            },
        ),
        migrations.CreateModel(
            name='FloodZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên điểm ngập')),
                ('zone_type', models.CharField(choices=[('black', 'Điểm đen ngập lụt'), ('frequent', 'Thường xuyên ngập'), ('seasonal', 'Ngập theo mùa'), ('rain', 'Ngập khi mưa lớn'), ('tide', 'Ngập triều cường')], max_length=20, verbose_name='Loại ngập')),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='Khu vực ngập')),
                ('district', models.CharField(max_length=100, verbose_name='Quận')),
                ('ward', models.CharField(blank=True, max_length=100, verbose_name='Phường')),
                ('street', models.CharField(blank=True, max_length=200, verbose_name='Tên đường/phố')),
                ('max_depth_cm', models.FloatField(default=50, verbose_name='Độ sâu tối đa (cm)')),
                ('avg_duration_hours', models.FloatField(default=3, verbose_name='Thời gian ngập trung bình (giờ)')),
                ('flood_cause', models.CharField(default='Hệ thống thoát nước quá tải', max_length=100, verbose_name='Nguyên nhân ngập')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang có nguy cơ')),
                ('last_flood_date', models.DateField(blank=True, null=True, verbose_name='Ngày ngập gần nhất')),
                ('last_reported_at', models.DateTimeField(blank=True, null=True, verbose_name='Báo cáo gần nhất')),
                ('report_count', models.IntegerField(default=0, verbose_name='Số báo cáo')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả chi tiết')),
                ('solution', models.TextField(blank=True, verbose_name='Biện pháp xử lý')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Điểm ngập',
                'verbose_name_plural': 'Các điểm ngập',
                'indexes': [models.Index(fields=['is_active'], name='hanoi_map_f_is_acti_04fdc3_idx'), models.Index(fields=['district'], name='hanoi_map_f_distric_9603e4_idx')],
            },
        ),
        migrations.CreateModel(
            name='FloodReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Vị trí báo cáo')),
                ('address', models.TextField(verbose_name='Địa chỉ chi tiết')),
                ('district', models.CharField(max_length=100, verbose_name='Quận/Huyện')),
                ('ward', models.CharField(blank=True, max_length=100, verbose_name='Phường/Xã')),
                ('street', models.CharField(blank=True, max_length=200, verbose_name='Tên đường')),
                ('water_depth', models.FloatField(verbose_name='Độ sâu nước (cm)')),
                ('severity', models.CharField(choices=[('light', 'Nhẹ (dưới 20cm)'), ('medium', 'Trung bình (20-40cm)'), ('heavy', 'Nặng (40-70cm)'), ('severe', 'Rất nặng (trên 70cm)')], max_length=20, verbose_name='Mức độ')),
                ('area_size', models.CharField(help_text='VD: 10m, cả mặt đường, 1 làn đường...', max_length=50, verbose_name='Diện tích ngập')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả tình hình')),
                ('photo_url', models.URLField(blank=True, verbose_name='Link ảnh')),
                ('video_url', models.URLField(blank=True, verbose_name='Link video')),
                ('reporter_name', models.CharField(blank=True, max_length=100, verbose_name='Tên người báo')),
                ('reporter_phone', models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại')),
                ('reporter_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('status', models.CharField(choices=[('pending', '⏳ Chờ xác nhận'), ('verified', '✅ Đã xác nhận'), ('false', '❌ Sai thông tin'), ('resolved', '🏁 Đã xử lý')], default='pending', max_length=20)),
                ('verification_notes', models.TextField(blank=True, verbose_name='Ghi chú xác nhận')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xác nhận')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Xác nhận bởi')),
                ('flood_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='hanoi_map.floodzone', verbose_name='Thuộc điểm ngập')),
            ],
            options={
                'verbose_name': 'Báo cáo ngập',
                'verbose_name_plural': 'Báo cáo ngập',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='hanoi_map_f_status_0177f0_idx'), models.Index(fields=['district', 'severity'], name='hanoi_map_f_distric_000fe6_idx')],
            },
        ),
    ]
