# Generated by Django 6.0 on 2025-12-15 02:48

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedFlooding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên điểm ngập cố định', max_length=200, verbose_name='Tên điểm ngập')),
                ('flood_type', models.CharField(choices=[('rain', 'Ngập do mưa'), ('tide', 'Ngập do triều'), ('river', 'Ngập do sông'), ('drainage', 'Ngập do thoát nước'), ('sewer', 'Ngập do cống'), ('urban', 'Ngập đô thị')], default='rain', max_length=20, verbose_name='Loại ngập')),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='Điểm trung tâm khu vực ngập', srid=4326, verbose_name='Vị trí trung tâm')),
                ('address', models.CharField(max_length=300, verbose_name='Địa chỉ')),
                ('district', models.CharField(max_length=100, verbose_name='Quận/Huyện')),
                ('ward', models.CharField(blank=True, max_length=100, verbose_name='Phường/Xã')),
                ('street', models.CharField(blank=True, max_length=200, verbose_name='Đường')),
                ('radius_meters', models.FloatField(default=50, help_text='Bán kính khu vực ngập từ điểm trung tâm (1-1000m)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Bán kính ảnh hưởng (m)')),
                ('rainfall_threshold_mm', models.FloatField(help_text='Lượng mưa tối thiểu để kích hoạt cảnh báo ngập', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(500)], verbose_name='Ngưỡng mưa kích hoạt (mm/h)')),
                ('predicted_depth_cm', models.FloatField(default=30.0, help_text='Độ sâu nước dự đoán khi vượt ngưỡng', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)], verbose_name='Độ sâu dự đoán (cm)')),
                ('duration_hours', models.FloatField(default=2.0, help_text='Thời gian ngập dự kiến sau khi mưa', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(72)], verbose_name='Thời gian ngập dự kiến (giờ)')),
                ('severity', models.CharField(choices=[('low', 'Thấp'), ('medium', 'Trung bình'), ('high', 'Cao'), ('very_high', 'Rất cao')], default='medium', max_length=20, verbose_name='Mức độ nghiêm trọng')),
                ('description', models.TextField(blank=True, help_text='Mô tả chi tiết về điểm ngập', verbose_name='Mô tả')),
                ('recommendations', models.TextField(blank=True, help_text='Khuyến nghị cho người dân khi khu vực này ngập', verbose_name='Khuyến nghị')),
                ('is_active', models.BooleanField(default=False, help_text='Đang trong trạng thái cảnh báo ngập', verbose_name='Đang cảnh báo')),
                ('is_monitored', models.BooleanField(default=True, help_text='Điểm ngập có được hệ thống giám sát tự động', verbose_name='Được giám sát')),
                ('flood_history', models.JSONField(default=list, help_text='Danh sách các lần ngập đã xảy ra', verbose_name='Lịch sử ngập')),
                ('activation_count', models.IntegerField(default=0, verbose_name='Số lần kích hoạt')),
                ('last_activated', models.DateTimeField(blank=True, null=True, verbose_name='Kích hoạt lần cuối')),
                ('last_deactivated', models.DateTimeField(blank=True, null=True, verbose_name='Tắt cảnh báo lần cuối')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('managed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_floodings', to=settings.AUTH_USER_MODEL, verbose_name='Quản lý bởi')),
            ],
            options={
                'verbose_name': 'Điểm ngập cố định',
                'verbose_name_plural': 'Điểm ngập cố định',
                'ordering': ['-is_active', 'severity', 'district'],
            },
        ),
        migrations.CreateModel(
            name='FloodZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên điểm ngập')),
                ('zone_type', models.CharField(choices=[('black', 'Điểm đen ngập lụt'), ('frequent', 'Thường xuyên ngập'), ('seasonal', 'Ngập theo mùa'), ('rain', 'Ngập khi mưa lớn'), ('tide', 'Ngập triều cường')], max_length=20, verbose_name='Loại ngập')),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='Khu vực ngập')),
                ('district', models.CharField(max_length=100, verbose_name='Phường')),
                ('ward', models.CharField(blank=True, max_length=100, verbose_name='Xã')),
                ('street', models.CharField(blank=True, max_length=200, verbose_name='Tên đường/phố')),
                ('max_depth_cm', models.FloatField(default=50, verbose_name='Độ sâu tối đa (cm)')),
                ('avg_duration_hours', models.FloatField(default=3, verbose_name='Thời gian ngập trung bình (giờ)')),
                ('flood_cause', models.CharField(default='Hệ thống thoát nước quá tải', max_length=100, verbose_name='Nguyên nhân ngập')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang có nguy cơ')),
                ('last_flood_date', models.DateField(blank=True, null=True, verbose_name='Ngày ngập gần nhất')),
                ('last_reported_at', models.DateTimeField(blank=True, null=True, verbose_name='Báo cáo gần nhất')),
                ('report_count', models.IntegerField(default=0, verbose_name='Số báo cáo')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả chi tiết')),
                ('solution', models.TextField(blank=True, verbose_name='Biện pháp xử lý')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Điểm ngập',
                'verbose_name_plural': 'Các điểm ngập',
                'indexes': [models.Index(fields=['is_active'], name='hanoi_map_f_is_acti_04fdc3_idx'), models.Index(fields=['district'], name='hanoi_map_f_distric_9603e4_idx')],
            },
        ),
        migrations.CreateModel(
            name='FloodReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Vị trí báo cáo')),
                ('address', models.TextField(verbose_name='Địa chỉ chi tiết')),
                ('district', models.CharField(max_length=100, verbose_name='Phường')),
                ('ward', models.CharField(blank=True, max_length=100, verbose_name='Xã')),
                ('street', models.CharField(blank=True, max_length=200, verbose_name='Tên đường')),
                ('water_depth', models.FloatField(verbose_name='Độ sâu nước (cm)')),
                ('severity', models.CharField(choices=[('light', 'Nhẹ (dưới 20cm)'), ('medium', 'Trung bình (20-40cm)'), ('heavy', 'Nặng (40-70cm)'), ('severe', 'Rất nặng (trên 70cm)')], max_length=20, verbose_name='Mức độ')),
                ('area_size', models.CharField(help_text='VD: 10m, cả mặt đường, 1 làn đường...', max_length=50, verbose_name='Diện tích ngập')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả tình hình')),
                ('photo_url', models.URLField(blank=True, verbose_name='Link ảnh')),
                ('video_url', models.URLField(blank=True, verbose_name='Link video')),
                ('reporter_name', models.CharField(blank=True, max_length=100, verbose_name='Tên người báo')),
                ('reporter_phone', models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại')),
                ('reporter_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('status', models.CharField(choices=[('pending', '⏳ Chờ xác nhận'), ('verified', '✅ Đã xác nhận'), ('false', '❌ Sai thông tin'), ('resolved', '🏁 Đã xử lý')], default='pending', max_length=20)),
                ('verification_notes', models.TextField(blank=True, verbose_name='Ghi chú xác nhận')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xác nhận')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('user', 'Người dân'), ('fixed_flooding_auto', 'FixedFlooding tự động'), ('fixed_flooding_admin', 'FixedFlooding từ admin'), ('prediction', 'Dự đoán'), ('sensor', 'Cảm biến'), ('manual', 'Thủ công')], default='user', max_length=50, verbose_name='Nguồn báo cáo')),
                ('confidence_score', models.FloatField(default=1.0, help_text='Độ tin cậy của báo cáo (0-1)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Độ tin cậy')),
                ('estimated_duration_hours', models.FloatField(default=2.0, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(72)], verbose_name='Thời gian ngập ước tính (giờ)')),
                ('is_active', models.BooleanField(default=True, help_text='Cảnh báo này còn hiệu lực không', verbose_name='Đang hoạt động')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Xác nhận bởi')),
                ('flood_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='hanoi_map.floodzone', verbose_name='Thuộc điểm ngập')),
            ],
            options={
                'verbose_name': 'Báo cáo ngập',
                'verbose_name_plural': 'Báo cáo ngập',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FloodPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Vị trí dự đoán')),
                ('address', models.CharField(max_length=300, verbose_name='Địa chỉ')),
                ('district', models.CharField(max_length=100, verbose_name='Quận')),
                ('ward', models.CharField(blank=True, max_length=100, verbose_name='Phường')),
                ('prediction_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời điểm dự đoán')),
                ('valid_until', models.DateTimeField(help_text='Thời gian dự đoán còn hiệu lực', verbose_name='Có hiệu lực đến')),
                ('risk_level', models.CharField(choices=[('very_low', 'Rất thấp'), ('low', 'Thấp'), ('medium', 'Trung bình'), ('high', 'Cao'), ('very_high', 'Rất cao')], max_length=20, verbose_name='Mức độ nguy cơ')),
                ('predicted_depth_cm', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)], verbose_name='Độ sâu dự đoán (cm)')),
                ('confidence', models.FloatField(default=70.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Độ tin cậy (%)')),
                ('rainfall_mm', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Lượng mưa (mm/h)')),
                ('rainfall_duration_hours', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Thời gian mưa (giờ)')),
                ('elevation', models.FloatField(help_text='So với mực nước biển', verbose_name='Độ cao (m)')),
                ('distance_to_river', models.FloatField(default=1000, verbose_name='Khoảng cách đến sông (m)')),
                ('drainage_capacity', models.CharField(choices=[('good', 'Tốt'), ('average', 'Trung bình'), ('poor', 'Kém'), ('very_poor', 'Rất kém')], default='average', max_length=20, verbose_name='Khả năng thoát nước')),
                ('reasons', models.JSONField(default=list, help_text='Danh sách nguyên nhân gây ngập', verbose_name='Nguyên nhân dự đoán')),
                ('recommendations', models.TextField(blank=True, verbose_name='Khuyến nghị')),
                ('affected_areas', models.TextField(blank=True, help_text='Mô tả chi tiết khu vực bị ảnh hưởng', verbose_name='Khu vực ảnh hưởng')),
                ('warning_triggered', models.BooleanField(default=False, verbose_name='Đã kích hoạt cảnh báo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Còn hiệu lực')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fixed_flooding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions', to='hanoi_map.fixedflooding', verbose_name='Điểm ngập cố định liên quan')),
                ('flood_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions', to='hanoi_map.floodzone', verbose_name='Vùng ngập liên quan')),
            ],
            options={
                'verbose_name': 'Dự đoán ngập',
                'verbose_name_plural': 'Dự đoán ngập',
                'ordering': ['-prediction_time'],
            },
        ),
        migrations.CreateModel(
            name='FloodHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Vị trí')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Địa chỉ')),
                ('district', models.CharField(max_length=100, verbose_name='Quận')),
                ('flood_type', models.CharField(max_length=50, verbose_name='Loại ngập')),
                ('rainfall_mm', models.FloatField(blank=True, null=True, verbose_name='Lượng mưa (mm/h)')),
                ('water_depth_cm', models.FloatField(verbose_name='Độ sâu nước (cm)')),
                ('duration_minutes', models.IntegerField(verbose_name='Thời gian ngập (phút)')),
                ('affected_area_sqm', models.FloatField(blank=True, null=True, verbose_name='Diện tích ảnh hưởng (m²)')),
                ('start_time', models.DateTimeField(verbose_name='Thời điểm bắt đầu')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm kết thúc')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời điểm ghi nhận')),
                ('source', models.CharField(choices=[('report', 'Báo cáo'), ('prediction', 'Dự đoán'), ('sensor', 'Cảm biến'), ('fixed', 'Điểm cố định'), ('manual', 'Thủ công')], max_length=20, verbose_name='Nguồn dữ liệu')),
                ('source_id', models.CharField(blank=True, help_text='ID của bản ghi gốc (report ID, prediction ID, etc.)', max_length=100, verbose_name='ID nguồn')),
                ('severity', models.CharField(choices=[('light', 'Nhẹ (dưới 20cm)'), ('medium', 'Trung bình (20-40cm)'), ('heavy', 'Nặng (40-70cm)'), ('severe', 'Rất nặng (trên 70cm)')], max_length=20, verbose_name='Mức độ')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('impact_level', models.CharField(choices=[('minor', 'Nhẹ'), ('moderate', 'Trung bình'), ('major', 'Nặng'), ('severe', 'Nghiêm trọng')], default='minor', max_length=20, verbose_name='Mức độ ảnh hưởng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_fixed_flooding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hanoi_map.fixedflooding', verbose_name='Điểm cố định liên quan')),
                ('related_prediction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hanoi_map.floodprediction', verbose_name='Dự đoán liên quan')),
                ('related_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='histories', to='hanoi_map.floodreport', verbose_name='Báo cáo liên quan')),
                ('related_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='hanoi_map.floodzone', verbose_name='Vùng ngập liên quan')),
            ],
            options={
                'verbose_name': 'Lịch sử ngập',
                'verbose_name_plural': 'Lịch sử ngập',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='fixedflooding',
            name='flood_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_floodings', to='hanoi_map.floodzone', verbose_name='Vùng ngập liên quan'),
        ),
        migrations.AddIndex(
            model_name='floodreport',
            index=models.Index(fields=['status', 'created_at'], name='hanoi_map_f_status_0177f0_idx'),
        ),
        migrations.AddIndex(
            model_name='floodreport',
            index=models.Index(fields=['district', 'severity'], name='hanoi_map_f_distric_000fe6_idx'),
        ),
        migrations.AddIndex(
            model_name='floodprediction',
            index=models.Index(fields=['risk_level', 'prediction_time'], name='hanoi_map_f_risk_le_8bfa9d_idx'),
        ),
        migrations.AddIndex(
            model_name='floodprediction',
            index=models.Index(fields=['district', 'warning_triggered'], name='hanoi_map_f_distric_460939_idx'),
        ),
        migrations.AddIndex(
            model_name='floodprediction',
            index=models.Index(fields=['is_active', 'valid_until'], name='hanoi_map_f_is_acti_2d3e78_idx'),
        ),
        migrations.AddIndex(
            model_name='floodhistory',
            index=models.Index(fields=['timestamp', 'location'], name='hanoi_map_f_timesta_fc829c_idx'),
        ),
        migrations.AddIndex(
            model_name='floodhistory',
            index=models.Index(fields=['district', 'start_time'], name='hanoi_map_f_distric_148cf8_idx'),
        ),
        migrations.AddIndex(
            model_name='floodhistory',
            index=models.Index(fields=['source', 'severity'], name='hanoi_map_f_source_d67f43_idx'),
        ),
        migrations.AddIndex(
            model_name='fixedflooding',
            index=models.Index(fields=['is_active', 'district'], name='hanoi_map_f_is_acti_1a74f1_idx'),
        ),
        migrations.AddIndex(
            model_name='fixedflooding',
            index=models.Index(fields=['rainfall_threshold_mm'], name='hanoi_map_f_rainfal_a4b610_idx'),
        ),
        migrations.AddIndex(
            model_name='fixedflooding',
            index=models.Index(fields=['severity'], name='hanoi_map_f_severit_6eb49a_idx'),
        ),
    ]
