# Generated by Django 6.0 on 2025-12-15 07:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanoi_map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='floodprediction',
            name='current_depth_cm',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Độ sâu hiện tại (cm)'),
        ),
        migrations.AddField(
            model_name='floodprediction',
            name='drainage_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm bắt đầu rút nước'),
        ),
        migrations.AddField(
            model_name='floodprediction',
            name='estimated_drainage_time_hours',
            field=models.FloatField(blank=True, default=0, help_text='Dự đoán thời gian để nước rút hết', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Thời gian cạn dự kiến (giờ)'),
        ),
        migrations.AddField(
            model_name='floodprediction',
            name='flood_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions', to='hanoi_map.floodreport', verbose_name='Báo cáo ngập liên quan'),
        ),
        migrations.AddField(
            model_name='floodprediction',
            name='last_depth_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cập nhật độ sâu lần cuối'),
        ),
    ]
